### ISSUE TITLE
Bug with Forbidden Lands system: Cannot destructure property 'desc' of 'this.getEstimation(...)' as it is undefined.

### ISSUE THREAD

**Issue by yjeroen** [mclemente/healthEstimate#109]
foundry.js:747 TypeError: Cannot destructure property 'desc' of 'this.getEstimation(...)' as it is undefined.
![image](https://user-images.githubusercontent.com/1303988/200181187-3b30894a-e312-41cb-bd2c-db6ed2ab6600.png)

Happens when hovering over a Forbidden Lands Party Sheet. 

Foundry v10
Forbidden Lands system 10.0.1

**Comment by yjeroen** [comment]
module setting for health is based on a different actor sheet (player or monster sheets both work without error)

![image](https://user-images.githubusercontent.com/1303988/200181311-d64a701b-ec36-43ab-b093-3443e56b337c.png)

**Comment by mclemente** [comment]
Try `actor.system.attribute.strength`.

**Comment by yjeroen** [comment]
@mclemente No difference. If you need any other logs feel free to let me know.

**Comment by mclemente** [comment]
It's `attribute`, not `attributes`.
![image](https://user-images.githubusercontent.com/5288872/200183377-06c39809-f014-45ee-a9a6-d53a3e9876a9.png)

**Comment by yjeroen** [comment]
So to clear my expectations:

- Foro ther sheet types (**Character**/**Monster**) the module works correctly
- On a sheet type where `actor.system.attribute.strength` is not working (like the **Party** or **Stronghold** type), I'd expect a **warning** not an error thrown in the console.
![image](https://user-images.githubusercontent.com/1303988/200183439-6eaa94c3-054e-4081-a094-b3e627867c03.png)

- I'd not expect these types of errors as well. I think error catching is missing on that usecase?
![image](https://user-images.githubusercontent.com/1303988/200183481-4a396a6c-665e-441e-b9c7-fe4716f9992f.png)

**Comment by mclemente** [comment]
I just pushed a fix for this issue, update the module and it should work as you expect.

**Comment by yjeroen** [comment]
Thanks a lot for the support!
However, it's still throwing the same errors.

I don't see `forbidden-lands` included in systemSpecifics.js, I think you made a saving error. :)

![image](https://user-images.githubusercontent.com/1303988/200192673-c7b72447-222d-48ae-89f6-2e807e467340.png)


![image](https://user-images.githubusercontent.com/1303988/200192540-ca2e668b-0576-409c-aae8-823cc74de444.png)

**Comment by mclemente** [comment]
Sorry, I've created the actual file and forgot to update the SystemSpecifics.
