### ISSUE TITLE
Positioning of text is off when using hexes

### ISSUE THREAD

**Issue by dirusulixes** [mclemente/healthEstimate#19]
fvtt 0.8.7
health estimate 2.5.8

the text positioning is off on both axes when the estimate is rendered on a hex map:
![image](https://user-images.githubusercontent.com/5693623/122256052-998e0500-cec6-11eb-8354-6b31081c1b64.png)

**Comment by mclemente** [comment]
Thank you, it should be fixed on the next update.

**Comment by dirusulixes** [comment]
tested now with 2.5.9. It's definitely much better, but I think it's still not fully centred for me:
![image](https://user-images.githubusercontent.com/5693623/122295625-5a28de00-cef1-11eb-9672-c4736dd144a5.png)

**Comment by mclemente** [comment]
I noticed my results weren't exactly like yours but I hoped it would work fine for you.
The odd thing is that it isn't that off-centered for me (maybe half a pixel or so).
Here's my results with the same settings as yours (Outline 0, x-large, Middle, -1):
![image](https://user-images.githubusercontent.com/5288872/122297544-05c23600-ced2-11eb-9633-6eeaa1811a03.png)

It might be off by a pixel at most, but it's nothing like yours.
![image](https://user-images.githubusercontent.com/5288872/122297747-4752e100-ced2-11eb-9d2c-3f5b92142b96.png)

Could you also test it with the Hexagonal Columns grid type and tell me if they're also off-center? I haven't changed them at all on the update because they showed fine for me.

**Comment by dirusulixes** [comment]
I think the issue is magnified at higher grid sizes. 

Here is 100px for me:
![Screenshot-20210617195105-327x383](https://user-images.githubusercontent.com/5693623/122456878-f3b1c780-cfa5-11eb-9010-c00decae523f.png)

And 150px:
![Screenshot-20210617195206-307x363](https://user-images.githubusercontent.com/5693623/122456912-fdd3c600-cfa5-11eb-831d-d32f097c5c73.png)

I can confirm that hex columns grid renders the text centred at all grid sizes.
